# Generated by Django 5.2.4 on 2025-08-04 19:59

import cloudinary_storage.storage
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import web.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_name', models.CharField(max_length=100)),
                ('under_name', models.CharField(max_length=60)),
                ('position_number', models.IntegerField(blank=True, null=True)),
                ('video_url', models.URLField()),
                ('lecture', models.CharField(blank=True, default='До цього уроку наразі немає лекції.', max_length=712, null=True)),
                ('homework', models.CharField(blank=True, default='До цього уроку наразі немає ДЗ.', max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(blank=True, default=False, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)])),
                ('user_email', models.EmailField(max_length=254)),
                ('is_activated', models.BooleanField(blank=True, default=False, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscribeTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('with_startbox', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_checked', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(blank=True, default='system_files/not_found', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=web.models.upload_homework_images)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('text', models.CharField(blank=True, default='Користувач відправив дз без запитань.', max_length=512, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_works', to=settings.AUTH_USER_MODEL)),
                ('lecture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_works', to='web.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='HomeWorkReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.CharField(blank=True, max_length=155, null=True)),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('data', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='web.homework')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('image', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=web.models.upload_message_image)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_read_user', models.BooleanField(blank=True, default=False, null=True)),
                ('is_read_admin', models.BooleanField(blank=True, default=False, null=True)),
                ('from_admin', models.BooleanField(blank=True, default=False, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='web.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(14)])),
                ('is_activated', models.BooleanField(blank=True, default=False, null=True)),
                ('activated_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('tariff', models.CharField(choices=[('base', 'Base'), ('pro', 'Pro'), ('master', 'Master')], default='base', max_length=10)),
                ('start_box_coupon_is_activated', models.BooleanField(blank=True, default=False, null=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='web.order')),
            ],
        ),
        migrations.CreateModel(
            name='StartBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('is_sent', models.BooleanField(blank=True, default=False, null=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_boxes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
