# Generated by Django 5.2.4 on 2025-08-04 20:52

import cloudinary_storage.storage
import web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='image',
            field=models.ImageField(blank=True, default='system_files/not_found', max_length=300, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=web.models.upload_homework_images),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=web.models.upload_message_image),
        ),
    ]
