# Generated by Django 5.2.4 on 2025-08-16 10:53

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_homework_image_alter_message_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LendingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=15)),
                ('lecture_name', models.CharField(max_length=50)),
                ('lecture_description', models.CharField(max_length=200)),
                ('preview', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='', verbose_name='landing_images/')),
                ('video_url', models.CharField(blank=True, max_length=255, null=True)),
                ('hello_video_id', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LendingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='landing_images/')),
            ],
        ),
        migrations.AddField(
            model_name='subscribetariff',
            name='user_friendly_name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='code',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code', to='web.order'),
        ),
        migrations.AlterField(
            model_name='code',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code', to='web.subscribetariff'),
        ),
    ]
