# Generated by Django 5.2.4 on 2025-08-16 11:45

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_lendingdata_lendingimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendingdata',
            name='lecture_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='lendingdata',
            name='preview',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='', verbose_name='lending_images/'),
        ),
        migrations.AlterField(
            model_name='lendingimage',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='lending_images/'),
        ),
        migrations.AlterField(
            model_name='subscribetariff',
            name='with_startbox',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
