# Generated by Django 5.2.4 on 2025-08-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_lendingdata_lecture_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lendingdata',
            name='video_url',
        ),
    ]
