# Generated by Django 5.2.4 on 2025-08-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_lendingdata_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingimage',
            name='direction',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lendingdata',
            name='lecture_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='subscribetariff',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
