# Generated by Django 5.2.4 on 2025-08-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_lendingimage_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='direction',
            field=models.CharField(blank=True, choices=[('tattoo', 'Тату'), ('piercing', 'Пірсинг')], default='tattoo', max_length=15),
        ),
        migrations.AddField(
            model_name='subscribetariff',
            name='direction',
            field=models.CharField(blank=True, default='tattoo', max_length=20),
        ),
    ]
