# Generated by Django 5.2.4 on 2025-08-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_lecture_direction_subscribetariff_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='direction',
            field=models.CharField(choices=[('tattoo', 'Тату'), ('piercing', 'Пірсинг')], default='tattoo', max_length=15),
        ),
    ]
