# Generated by Django 5.2.4 on 2025-08-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_lecture_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='startbox',
            name='direction',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
