# Generated by Django 5.2.4 on 2025-08-18 11:36

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_homeworkreview_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendingimage',
            name='image',
            field=models.ImageField(blank=True, max_length=350, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='lending_images/'),
        ),
    ]
