# Generated by Django 5.2.4 on 2025-08-18 11:38

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_lendingimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendingdata',
            name='preview',
            field=models.ImageField(blank=True, max_length=350, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='', verbose_name='lending_images/'),
        ),
    ]
