# Generated by Django 5.2.4 on 2025-08-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_lendingdata_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='homework',
            field=models.CharField(blank=True, default='До цього уроку наразі немає ДЗ.', max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture',
            field=models.CharField(blank=True, default='До цього уроку наразі немає лекції.', max_length=2012, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='under_name',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=1012),
        ),
    ]
