# Generated by Django 5.2.4 on 2025-08-04 20:52

import authentication.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='avatar',
            field=models.ImageField(blank=True, default='base_icon_k7nhiw', max_length=300, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=authentication.models.profile_avatar),
        ),
    ]
