# Generated by Django 5.2.4 on 2025-08-18 11:38

import authentication.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_usermodel_avatar_alter_usermodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='avatar',
            field=models.ImageField(blank=True, default='https://media.licdn.com/dms/image/v2/C5112AQEw1fXuabCTyQ/article-inline_image-shrink_1500_2232/article-inline_image-shrink_1500_2232/0/1581099611064?e=1759363200&v=beta&t=ff9zPQQdugK46aK3pNUbXCX49mGIU_bF5YhCfGTRBOU', max_length=350, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=authentication.models.profile_avatar),
        ),
    ]
